### ISSUE TITLE
What is happening with Repository About? 

### ISSUE THREAD

**Issue by Danielskry** [microsoft/Thoth#32]
What is happening with the repository's "About" section? Is it a random text from Wikipedia about Thoth?

> The Egyptians credited him as the author of all works of science, religion, philosophy, and magic. The Greeks further declared him the inventor of astronomy , astrology , the science of numbers, mathematics, geometry, surveying, medicine, botany, theology, civilized government, the alphabet, reading, writing, and oratory. 

![bilde](https://github.com/microsoft/Thoth/assets/15195014/a4fa5047-1cf0-4c82-81de-5efd17288b3c)

**Comment by juan-trujillo** [comment]
It is not random text from wikipedia, it is a well Thoth out extract from wikipedia.
